spring:
  application:
    name: reg
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:h2:mem:regdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
server:
  port: 8081