CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(64) PRIMARY KEY,
    email VARCHAR(64),
    parameter VARCHAR(16),
    city VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS notes (
    email VARCHAR(64) PRIMARY KEY,
    note VARCHAR(128)
);